---
#- name: set ntp server
#  copy: src=files/{{item}} dest=/etc/{{item}}
#  with_items:
#   - ntp.conf
#- name: chkconfig on
#  raw: service ntpd restart && chkconfig --level 35 ntpd on && ntpstat
- name: copy cm5.12.0
  copy: src=files/cm-5.12.0.tgz dest=/opt/
- name: tar xzvf cm5.12.0
  raw: cd /opt && tar -xzvf cm-5.12.0.tgz
- name: copy jmx_gateway
  copy: src=files/jdk1.8.0_45.tar.gz dest=/tmp/jdk1.8.0_45.tar.gz
- name: tar java
  raw: tar -zxf /tmp/jdk1.8.0_45.tar.gz -C /usr/local/
- name: chown java
  raw: chown -R root:root /usr/local/jdk1.8.0_45
- name: set java links
  raw: cd /usr/local  && ln -s /usr/local/jdk1.8.0_45  /usr/local/java
- name: copy bash shell
  copy : src=files/{{item}} dest=/opt/
  with_items:
    - blockdev.sh
- name : set blockdev
  raw : bash /opt/blockdev.sh 
- name : user scm user
  raw : useradd --system --home=/opt/cm-5.12.1/run/cloudera-scm-server/ --no-create-home --shell=/bin/false --comment "Cloudera SCM User" cloudera-scm
- name: satrt cm agent
  raw: /opt/cm-5.12.0/etc/init.d/cloudera-scm-agent start
