---
- name: clear old yum.repo
  raw: cd /etc/yum.repos.d && mkdir bak && mv *.repo bak/
- name: push mob
  copy: src={{item}} dest=/etc/yum.repos.d/{{item}}
  with_items:
    - mob.repo
    - nexus-centos.repo
- name: make cache
  raw: yum makecache
- name: set ntp server
  copy: src=files/{{item}} dest=/etc/{{item}}
  with_items:
   - ntp.conf
- name: install java
  copy: src=files/jdk1.7.0_67-cloudera.tar.gz dest=/tmp/jdk1.7.0_67-cloudera.tar.gz
- name: tar java 1.7
  raw: mkdir -p  /usr/java && tar  -zxf  /tmp/jdk1.7.0_67-cloudera.tar.gz  -C /usr/java/
- name: java 1.8.45
  copy: src=files/jdk1.8.0_45.tar.gz dest=/tmp/jdk1.8.0_45.tar.gz
- name: tar java
  raw: tar -zxf /tmp/jdk1.8.0_45.tar.gz -C /opt/
- name: java 1.8.181
  copy: src=files/jdk-8u181-linux-x64.tar.gz dest=/tmp/jdk-8u181-linux-x64.tar.gz
- name: tar java 1.8.181
  raw: tar -zxf /tmp/jdk-8u181-linux-x64.tar.gz -C /opt/
- name: chown java
  raw: chown -R root:root /opt/jdk1.8.0_181
- name: copy config
  copy: src=files/java.conf dest=/tmp/java.conf
- name: check profile
  raw: grep -q JAVA_HOME /etc/profile || cat /tmp/java.conf >> /etc/profile
- name: install cloudera-manager-agent-5.8.3
  yum: 
    name: 
      - cloudera-manager-agent-5.8.3
- name: config cloudera-scm-agent 
  raw: sed -i 's/server_host=localhost/server_host=10.6.161.34/' /etc/cloudera-scm-agent/config.ini
- name: set cloudera-scm-agent service start
  raw: /etc/init.d/cloudera-scm-agent start

