---
- name: copy pkgs and unarchive
  unarchive: src=files/{{ zookeeper_version }}.tar.gz dest=/data/apache remote_src=no owner=hadoop group=hadoop mode=0755
- name: create soft link
  file: src=/data/apache/{{ zookeeper_version }} dest=/data/apache/zookeeper state=link owner=hadoop group=hadoop mode=0755
- name: create zk dataDir
  file: path=/data/apache/data/zookeeper/datalogs state=directory owner=hadoop group=hadoop mode=0755
- name: create zk myid
  copy: dest=/data/apache/data/zookeeper/datalogs/myid content={{ id }} mode=0644
- name: do configure zoo.cfg
  template: src=zoo.cfg.j2 dest=/data/apache/{{ zookeeper_version }}/conf/zoo.cfg owner=hadoop group=hadoop mode=0644
- name: start Zookeeper
  raw: su - hadoop -c "/data/apache/{{ zookeeper_version }}/bin/zkServer.sh restart"