---
- name: copy hadoop-env.sh
  copy: src=files/hadoop-env.sh dest=/data/apache/hadoop/etc/hadoop/hadoop-env.sh owner=hadoop group=hadoop mode=0644

- name: copy core-site.xml
  copy: src=files/core-site.xml dest=/data/apache/hadoop/etc/hadoop/core-site.xml owner=hadoop group=hadoop mode=0644

- name: copy hdfs-site.xml
  copy: src=files/hdfs-site.xml dest=/data/apache/hadoop/etc/hadoop/hdfs-site.xml owner=hadoop group=hadoop mode=0644

- name: copy mapred-site.xml
  copy: src=files/mapred-site.xml dest=/data/apache/hadoop/etc/hadoop/mapred-site.xml owner=hadoop group=hadoop mode=0644

- name: copy yarn-site.xml
  copy: src=files/yarn-site.xml dest=/data/apache/hadoop/etc/hadoop/yarn-site.xml owner=hadoop group=hadoop mode=0644

- name: copy hadoop workers
  copy: src=files/workers dest=/data/apache/hadoop/etc/hadoop/workers owner=hadoop group=hadoop mode=0644

- name: copy hdfs-rbf-site.xml
  copy: src=files/hdfs-rbf-site.xml dest=/data/apache/hadoop/etc/hadoop/hdfs-rbf-site.xml owner=hadoop group=hadoop mode=0644
